### ISSUE TITLE
alpha version broken because of path changes in upstream repo

### ISSUE THREAD

**Issue by endreigesund** [YannickRe/azuredevops-buildagents#70] opened 2023-11-15 14:17 UTC
| Cannot find path '/agent/_work/1/s/runner-images/images/linux' because
     | it does not exist.

**Comment by YannickRe** [comment] 2023-11-15 14:38
Yes, this seems like a change that happened 4h ago. I will need to take the changes from https://github.com/actions/runner-images/blob/main/images.CI/linux-and-win/azure-pipelines/image-generation.yml and incorporate them into https://github.com/YannickRe/azuredevops-buildagents/blob/main/buildagent-generation-template.yml

**Comment by endreigesund** [comment] 2023-11-17 10:07
Seems a lot going on at the moment - https://github.com/actions/runner-images/issues/8706

Nice - do you have any eta of when you have time looking into it?  We are waiting to roll out new images with .net 8 :)  - current this is on prerelease and rolling out as we speak.

**Comment by erik-de-bont** [comment] 2023-11-19 00:17
@endreigesund  @YannickRe  I have updated the [buildagent-generation-template.yml ](https://github.com/erik-de-bont/azuredevops-buildagents/blob/main/buildagent-generation-template.yml) on my fork. I am now building a new image an alpha release of ubuntu 2004, which seems to work. I need to do some more testing before I do a pull request, please have a look at the new version on my fork.

**Comment by erik-de-bont** [comment] 2023-11-19 19:50
Making progress. The Image building is working with the setup. The generating a Gallery  VM not yet. 

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/71345042/2ac0f16d-478a-4796-8c59-ee091fca5aa7)

![image](https://github.com/YannickRe/azuredevops-buildagents/assets/71345042/69df072a-2bf0-4e04-9efc-355e3c7ae430)

**Comment by erik-de-bont** [comment] 2023-11-20 07:26
Fixed the last issue. Was able to generate an new alpha ubuntu 22.04 image. I have made a pull request for the new code.

**Comment by endreigesund** [comment] 2023-11-20 09:05
@erik-de-bont failed running from your fork now:
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/22214517/650e0855-1938-492a-b675-0974584a6166)

**Comment by erik-de-bont** [comment] 2023-11-20 09:27
@endreigesund  Thanks for the update. Let me know if works. My current status:

- Only works for alpha versions (version created 15 november and later) since the image make use of the new dir structure.
- Ubuntu image 22.04 created. Ubuntu image 20.04 currently running.
- Not been able to created to create Windows 2019 or 2022 yet. This doesn't seem to be related  to newbuildagent-generation-template.yml, but due to some installation scripts during the build. A SHA doesn't match the downloaded installation file, causing the image build to fail.

**Comment by endreigesund** [comment] 2023-11-20 12:50
since i'm running from devops i think must specify repository_base_path to azuredevops-buildagents or the repo won't downloading in this step:
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/22214517/8d4b193a-c166-45fc-bde3-f5fdc99612cf)
When specified it fails in build vm step
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/22214517/7154cfe9-8a93-4c62-99e1-39575757145f)

When not specifying parameter "repository_base_path" it runs build vm, but then fails in create image gallery step:
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/22214517/54cdcb10-bd7b-4714-9508-ea3a6c4a70a8)

So not able to use the new version from azure devops when templating pipeline from your repo

**Comment by erik-de-bont** [comment] 2023-11-20 13:08
@endreigesund  You should make your own fork or clone and run it from that repository.

**Comment by ianjirka** [comment] 2023-11-24 23:13
FWIW I'm having the same issue that @endreigesund is having when testing the changes from your branch.  

I do think repostiory_base_path is needed here because I can't reference buildagent-generation.yml from my own YAML pipeline, because it is not a template, and so fails when the parser sees elements like 'trigger'.

**Comment by ianjirka** [comment] 2023-11-25 01:24
On my build machine, the tree layout looks like this: 

```
.
├── azuredevops-buildagents
│   ├── CODE_OF_CONDUCT.md
│   ├── README.md
...
├── runner-images
```

Eg, runner-images is placed as a peer directory, not inside the resource repo.

In a forked repo, I updated the call to build-image.ps1 to reference it as `filePath: runner-images/images.CI/linux-and-win/build-image.ps1` - this allows buildVM to run.  I'll know in a bit whether the rest of the pipeline runs as well.

I don't know if this will break the case where you invoke buildagent-generation.yaml directly, though.  I don't have that setup.

**Comment by pippolino** [comment] 2023-11-25 13:43
With the @erik-de-bont's PR code it works correctly on release ubuntu 22.04. I wanted to make sure there were no regressions on windows but I'm having problems with this an know issue [8884](https://github.com/actions/runner-images/issues/8884)
![image](https://github.com/YannickRe/azuredevops-buildagents/assets/237308/1f7af11d-df57-4d89-ad46-5b865859c55b)

**Comment by ianjirka** [comment] 2023-11-30 03:53
> In a forked repo, I updated the call to build-image.ps1 to reference it as `filePath: runner-images/images.CI/linux-and-win/build-image.ps1` - this allows buildVM to run. I'll know in a bit whether the rest of the pipeline runs as well.

It took a while for me to validate because runner-images was broken for ubuntu for a bit.  These changes build successfully for me now.   I reference the -template.yaml from my own build pipeline because I created it back when that was the recommendation.

You can see the changes [here](https://github.com/ianjirka/azuredevops-buildagents/blob/usr/ianjirka/update_templates/buildagent-generation-template.yml).  Unfortunately the diff is a bit ugly because I didn't catch that my auto-formatter ran :|.  

@erik-de-bont, let me know what you think.  I can make a formatterless PR change if it's useful to you, but can't validate the case where the pipeline is set up using build-generation.yaml directly.

**Comment by endreigesund** [comment] 2023-11-30 23:04
@erik-de-bont @ianjirka  confirmed also from my side.. new paths solved this.

Do you normally run from alpha, prerelease or release tags? Seems to be a high failurerate on building this images.

**Comment by ianjirka** [comment] 2023-12-01 05:50
> @erik-de-bont @ianjirka confirmed also from my side.. new paths solved this.
> 
> Do you normally run from alpha, prerelease or release tags? Seems to be a high failurerate on building this images.

I only build release images.  I noticed the image build pipeline failing when investigating why .Net 8 wasn't on the build machine.

**Comment by mvpwasilewskim** [comment] 2023-12-05 18:22
Consider using alpha (main branch): https://github.com/actions/runner-images/discussions/8476#discussioncomment-7209143

**Comment by erik-de-bont** [comment] 2023-12-08 09:21
> @endreigesund Thanks for the update. Let me know if works. My current status:
> 
> * Only works for alpha versions (version created 15 november and later) since the image make use of the new dir structure.
> * Ubuntu image 22.04 created. Ubuntu image 20.04 currently running.
> * Not been able to created to create Windows 2019 or 2022 yet. This doesn't seem to be related  to newbuildagent-generation-template.yml, but due to some installation scripts during the build. A SHA doesn't match the downloaded installation file, causing the image build to fail.

Now able to create all Linux and Windows images with new directory structure

**Comment by aolmosj** [comment] 2023-12-14 08:38
Well, now there are even more changes, so it's broken again...

```
Attempting to modify C:\a\1\s\runner-images\images\windows\templates\windows-2019.json with workaround
Get-Content : Cannot find path 'C:\a\1\s\runner-images\images\windows\templates\windows-2019.json' because it does not 
exist.
```

They changed these json files, now they are hcl:

https://github.com/actions/runner-images/blob/main/images/windows/templates/windows-2022.pkr.hcl

**Comment by erik-de-bont** [comment] 2023-12-14 09:16
@aolmosj  Thanks for the heads up ! I have update the code in my fork (and Pull Request) to use  pkr.hcl templates. I am able to build the alpha images again. Pre-release and release are still using the json format. It usually takes 2-4 weeks  before the alpha images become release, so we are again in a transition perion.

**Comment by YannickRe** [comment] 2023-12-18 22:05
@erik-de-bont 's PR has been merged, and that should fix this issue.

**Closed by YannickRe** 2023-12-18 22:05 UTC
Labels: bug
